# Minimal Docker Compose configuration for MediQ Backend
services:
  server:
    build:
      context: .
    ports:
      - 7070:7070
    volumes:
      # Persist SQLite database
      - ./database.db:/app/database.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7070/health"]
      interval: 30s
      timeout: 10s
      retries: 3
