package com.softwareengineering.models.enums;

public enum Speciality {
    CARDIOLOGIST,
    DERMATOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    GYNECOLOGY,
    NEUROLOGIST,
    ONCOLOGIST,
    ORTHOPEDIST,
    OTORHINOLARYNGOLOGIST,
    PEDIATRICIAN,
    PSYCHIATRIST,
    RADIOLOGIST,
    UROLOGIST,
    ORNITHOLOGIST,
}
